name: Auto-close PRs

on:
  pull_request:
    types: [opened, reopened]

jobs:
  close-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      - name: Close PR and delete branch
        run: |
          gh pr close "$PR_URL" --delete-branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
